---
swagger: "2.0"
info:
  description: "Api for Unity - Swagger"
  version: "1.0.0"
  title: "Unity Swagger"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "user"
  description: "User Information"
- name: "monster"
  description: "Monster Information"
schemes:
- "http"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /user:
    get:
      tags:
      - "user"
      summary: "Get all user list"
      description: ""
      operationId: "userList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successfully load user info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        404:
          description: "user not found"
      x-swagger-router-controller: "User"
    post:
      tags:
      - "user"
      summary: "Add new User"
      description: ""
      operationId: "addUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "user object"
        required: true
        schema:
          $ref: "#/definitions/user"
      responses:
        200:
          description: "Success"
          schema:
           type: "array"
           items:
            $ref: "#/definitions/user"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "User"
    put:
      tags:
      - "user"
      summary: "Update User"
      description: ""
      operationId: "updateUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "user"
        description: "user object"
        required: true
        schema:
          $ref: "#/definitions/user"
      responses:
        200:
          description: "Successfully load user info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        400:
          description: "Invalid userId"
        404:
          description: "User not found"
      x-swagger-router-controller: "User"

  /user/{userId}:
    get:
      tags:
      - "user"
      summary: "Get user Info by userId"
      description: ""
      operationId: "getUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "user1 for test"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully load user info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        400:
          description: "Invalid userId"
        404:
          description: "User not found"
      x-swagger-router-controller: "User"
    delete:
      tags:
      - "user"
      summary: "Delete User Info by monsterId"
      description: ""
      operationId: "deleteUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "user1 for test"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully delete user info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/user"
        404:
          description: "User not found"
      x-swagger-router-controller: "User"
  /monster:
    get:
      tags:
      - "monster"
      summary: "Get Monster List"
      description: ""
      operationId: "monsterList"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successfully Load Monster List"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/monster"
      x-swagger-router-controller: "Monster"
    post:
      tags:
      - "monster"
      summary: "Add new Monster"
      description: ""
      operationId: "addMonster"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "monster"
        description: "monster object"
        required: true
        schema:
          $ref: "#/definitions/monster"
      responses:
        200:
          description: "Success"
          schema:
           type: "array"
           items:
            $ref: "#/definitions/monster"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "Monster"
    put:
      tags:
      - "monster"
      summary: "Update monster"
      description: ""
      operationId: "updateMonster"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "monster"
        description: "monster object"
        required: true
        schema:
          $ref: "#/definitions/monster"
      responses:
        200:
          description: "Successfully load monster info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/monster"
        400:
          description: "Invalid monsterId"
        404:
          description: "Monster not found"
      x-swagger-router-controller: "Monster"

  /monster/{monsterId}:
    get:
      tags:
      - "monster"
      summary: "Get monster Info by monsterId"
      description: ""
      operationId: "getMonster"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "monsterId"
        in: "path"
        description: "monster1 for test"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully load monster info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/monster"
        400:
          description: "Invalid monsterId"
        404:
          description: "Monster not found"
      x-swagger-router-controller: "Monster"
    delete:
      tags:
      - "monster"
      summary: "Delete monster Info by monsterId"
      description: ""
      operationId: "deleteMonster"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "monsterId"
        in: "path"
        description: "monster1 for test"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successfully delete monster info"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/monster"
        404:
          description: "Monster not found"
    x-swagger-router-controller: "Monster"
definitions:
  user:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "hogehoge"
      password:
        type: "string"
  monster:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        example: 1
      name:
        type: "string"
        example: "hogehoge"
      type:
        type: "string"
        example: "fire"
      rank:
        type: "integer"
        format: "int64"
        example: 3
